#general logging
logFolder: 'logs/'
logName: 'log'

#Sync Logging
#--optional
#syncLogFolder: 'syncLogs'
#syncLogName: 'syncLog'

#Backup Logging
#--optional
#backupLogFolder: 'backupLogs'
#backupLogName: 'backupLog'

#backup settings
backupName: 'backup-archive'