logFolder: 'logs/'
syncLogName: 'syncLog'
BackupLogName: 'backupLog'

syncSource: 'serverSource'
syncDestination: 'localDestination'

backupSource: 'backupSource'
backupDestination: 'backupDestination'
backupName: 'backup-archive'

startCommand: 'save-off'
finishCommand: 'save-on'