#---general logging---
#--optional--
#logFolder: 'logs/'
logName: 'log'

#---Sync Logging---
#--optional--
#syncLogFolder: 'syncLogs'
#syncLogName: 'syncLog'

#---Backup Logging---
#--optional--
#backupLogFolder: 'backupLogs'
#backupLogName: 'backupLog'

syncSource: 'serverSource'
syncDestination: 'localDestination'

#--Will use the syncDestination by default--
#backupSource: 'backupSource'
backupDestination: 'backupDestination'
backupName: 'backup-archive'

startCommand: 'save-off'
finishCommand: 'save-on'